application: gasole-app
version: release
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on
# - deferred: on

handlers:
# - url: /clean
#   script: clean_history.app
- url: /backends/update
  script: backends.app
- url: /robots.txt
  static_files: static/txt/robots.txt
  upload: static/txt/robots.txt
- url: /humans.txt
  static_files: static/txt/humans.txt
  upload: static/txt/humans.txt
- url: /tasks/history
  script: cron_update.app
  login: admin
- url: /tasks/update
  script: cron_update.app
  login: admin
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /css
  static_dir: static/css
- url: /js
  static_dir: static/js
- url: /img
  static_dir: static/img
- url: /icon
  static_dir: static/icon
- url: /font
  static_dir: static/font
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest
- name: lxml
  version: latest
  